baseURL = "/"
languageCode = "en-us"
title = "genezio"
theme = "genezio-theme"
paginate = 12

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
enableRobotsTXT = true

[build]
  writeStats = true

[params]
    primary_color = "#6f42c1"
    primary_light = "#ffffff"
    secondary_color = "#2a478b"
    secondary_light = "#d5d5e9"
    green_color = "#00faa4"
    grey_color = "#d5d5d5"
    carbon = "#2a478b"
    steel = "#2a478b"

    font_base = "'Inter'"
    font_heading = "'Inter'"

    [params.homepage_meta_tags]
        meta_description = "genezio helps you write your API, deploy it and generate the SDK for easy integration in your website/mobile app."
        meta_og_title = "The easy way to write, deploy and use a serverless API"
        meta_og_type = "website"
        meta_og_url = "https://genez.io"
        meta_og_image = "https://genez.io/images/og.jpg"
        meta_og_description = "genezio helps you write your API, deploy it and generate the SDK for easy integration in your website/mobile app."
        meta_twitter_card = "summary"
        meta_twitter_site = "@GenezioNetwork"
        meta_twitter_creator = "@GenezioNetwork"

    [params.global]
        header_fixed = true

    [params.footer]
        description = "genezio is a new paradigm in cloud native programming, making it accessible to everyone, allowing elegant and quick development of websites, mobile apps, IoT apps, and many others."
        facebook = "https://www.facebook.com/profile.php?id=100086667803855"
        twitter = "https://twitter.com/Geneziodev"
        instagram = "https://www.instagram.com/genezio.dev/"
        discord = "https://discord.com/invite/uc9H5YKjXv"
        linkedin = "https://www.linkedin.com/company/genez-io/"

    [params.homepage]
        show_features = true 
        features_title = "Seamless development of your serverless API"
        pricing_title = "Pricing Plans for Developers"
        get_started = "Get started now with genezio!"
        demo = "How to use genezio"
    
    [params.hero]
        hero_background_gradient_one = "#9477c4"
        hero_background_gradient_two = "#9477c4"


# Footer Menu Third
[[menu.footer_tertiary]]
    name = "Contact us at: contact@genez.io"
    url = "mailto:contact@genez.io"
    weight = 1

[[menu.footer_tertiary]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 2

[[menu.footer_tertiary]]
    name = "Terms & Conditions"
    url = "/eula/"
    weight = 3

[[menu.footer_tertiary]]
    name = "Brand Assets"
    url = "https://drive.google.com/drive/folders/1DUTEllKJygFyO3lsHi4uu703iZfYQHB5?usp=sharing"
    weight = 4
    
[permalinks]
    posts = "/blog/:title/"
