baseURL = "/"
languageCode = "en-us"
title = "genezio"
theme = "genezio-theme"
paginate = 12

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
enableRobotsTXT = true
disableHugoGeneratorInject = true

[build]
  writeStats = true

[params]
    primary_color = "#6f42c1"
    primary_light = "#ffffff"
    secondary_color = "#2a478b"
    secondary_light = "#d5d5e9"
    green_color = "#00faa4"
    grey_color = "#d5d5d5"
    carbon = "#2a478b"
    steel = "#2a478b"

    font_base = "'Inter'"
    font_heading = "'Inter'"

    [params.global]
        header_fixed = true

    [params.footer]
        description = "genezio is a new paradigm in cloud native programming, making it accessible to everyone, allowing elegant and quick development of websites, mobile apps, IoT apps, and many others."
        facebook = "https://www.facebook.com/profile.php?id=100086667803855"
        twitter = "https://twitter.com/Geneziodev"
        instagram = "https://www.instagram.com/genezio.dev/"
        discord = "https://discord.com/invite/uc9H5YKjXv"
        linkedin = "https://www.linkedin.com/company/genez-io/"

    
    [params.hero]
        hero_background_gradient_one = "#9477c4"
        hero_background_gradient_two = "#9477c4"


# Footer Pages 
[[menu.footer_pages]]
    name = "Genezio Documentation"
    url = "https://docs.genez.io/genezio-documentation/"
    weight = 1

[[menu.footer_pages]]
    name = "Full Stack Dart App"
    url = "/full-stack-dart-application/"
    weight = 2

[[menu.footer_pages]]
    name = "Landing Page"
    url = "/"
    weight = 3

# Footer Menu Third
[[menu.footer_tertiary]]
    name = "Contact us at: contact@genez.io"
    url = "mailto:contact@genez.io"
    weight = 1

[[menu.footer_tertiary]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 2

[[menu.footer_tertiary]]
    name = "Terms & Conditions"
    url = "/eula/"
    weight = 3

[[menu.footer_tertiary]]
    name = "Brand Assets"
    url = "https://drive.google.com/drive/folders/1DUTEllKJygFyO3lsHi4uu703iZfYQHB5?usp=sharing"
    weight = 4

[permalinks]
    posts = "/blog/:title/"
