baseURL = "/"
languageCode = "en-us"
title = "genez.io"
theme = "hugo-shard"
paginate = 12

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[params]
    primary_color = "#9477c4"
    primary_light = "#fffff8"
    secondary_color = "#2a478b"
    secondary_light = "#d5d5e9"
    grey_color = "#d5d5d5"
    carbon = "#2a478b"
    steel = "#2a478b"

    font_base = "'Lato'"
    font_heading = "'Roboto'"

    google_analytics_id = ""

    [params.homepage_meta_tags]
        meta_description = "A brilliant, modern Hugo theme for startups."
        meta_og_title = "Hugo Shard Theme"
        meta_og_type = "website"
        meta_og_url = "https://hugo-shard.netlify.com"
        meta_og_image = "https://hugo-shard.netlify.com/images/tn.png"
        meta_og_description = "A brilliant, modern Hugo theme for startups."
        meta_twitter_card = "summary"
        meta_twitter_site = "@zerostaticio"
        meta_twitter_creator = "@zerostaticio"

    [params.global]
        header_fixed = true

    [params.footer]
        show_zerostatic_link = true
        show_footer_logo = true
        description = "Hugo Shard is startup theme for the Hugo static site generator. It is a purpose built startup archetype with on trend design asthetics."
        show_menu_footer_primary = true
        footer_primary_heading = "Product"
        show_menu_footer_secondary = true
        footer_secondary_heading = "Company"
        show_menu_footer_tertiary = true
        footer_tertiary_heading = "Support"
        show_social_media_links = true
        facebook = false
        twitter = "https://twitter.com/zerostaticio"
        angellist = "https://angelist.com"
        linkedin = "https://www.linkedin.com"

    [params.homepage]
        show_features = true 
        features_title = "Seamless development of your backend functions"
    
    [params.hero]
        hero_background_gradient_one = "#2b3af7"
        hero_background_gradient_two = "#2b8cf7"

# Main Menu
[[menu.main]]
	name = "Product"
	url = "/product/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3

# Footer Menu Primary
[[menu.footer_primary]]
	name = "Home"
	url = "/"
    weight = 1

[[menu.footer_primary]]
	name = "Product"
	url = "/product/"
    weight = 2

# Footer Menu Secondary
[[menu.footer_secondary]]
    name = "Blog"
    url = "/posts/"
    weight = 1

[[menu.footer_secondary]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.footer_secondary]]
    name = "Page 2"
    url = "/culture/"
    weight = 3
    
[[menu.footer_secondary]]
    name = "Page 3"
    url = "/page3/"
    weight = 4

[[menu.footer_secondary]]
    name = "Page 4"
    url = "/page4/"
    weight = 5

# Footer Menu Third
[[menu.footer_tertiary]]
    name = "Contact"
    url = "/contact/"
    weight = 1

[[menu.footer_tertiary]]
    name = "Privacy Policy"
    url = "/privacy/"
    weight = 2

[[menu.footer_tertiary]]
    name = "Terms Of Service"
    url = "/terms-of-service/"
    weight = 3
    
[permalinks]
    post = "/:year/:month/:title/"

[taxonomies]
    tag = "tags"
    category = "categories"
    author = "authors"
  
