name = "Genezio"
description = "The Coolest Way to Write, Deploy and Use a Serverless API."
homepage = "https://genez.io"
tags = ["startup","responsive","minimal","business","company","bootstrap"]
features = ["cloud"]
min_version = 0.51

[author]
  name = "Genezio"
  homepage = "https://genez.io"